### ISSUE TITLE
do you have all versions of gps's implementation

### ISSUE THREAD

**Issue by dujinyu** [hanyas/trajopt#2]
do you have all versions of gps's implementation?

**Comment by hanyas** [comment]
What do you mean? What versions are you referring to?

**Comment by dujinyu** [comment]
Guided Policy Search(GPS)
Variational Policy Search via Trajectory Optimization(vGPS)
Learning Complex Neural Network Policies with Trajectory Optimization(cGPS)
I mean the implementation of the above three papers

**Comment by hanyas** [comment]
No this repository only implements the core of GPS, what is referred to as called Maximum Entropy iLQG. The iterative trajectory optimization via dynamic programming.

**Comment by dujinyu** [comment]
Is this repo based on an article you published? I find some new abbreviations, such as elqr, bspilqr.

**Comment by hanyas** [comment]
No, the implementations are not really related to a publication directly. Although you can find more explanation on Max-Entropy iLQG here:
[https://www.ias.informatik.tu-darmstadt.de/uploads/Site/EditPublication/Abdulsamad_ICAPS_2017.pdf](url)

And here:
[https://www.ias.informatik.tu-darmstadt.de/uploads/Site/EditPublication/Abdulsamad_Master_Thesis_2016.pdf](url)

The names eLQR and bsp-iLQR stand for Extended LQR and Belief-Space iLQR by Jur Van den Berg:
[https://www.researchgate.net/publication/258140864_Motion_Planning_under_Uncertainty_Using_Iterative_Local_Optimization_in_Belief_Space](url)

Also, if you are interested in robust trajectory optimization techniques check our latest paper on the subject: 
[https://www.ias.informatik.tu-darmstadt.de/uploads/Team/JoeWatson/Watson19I2c.pdf](url)

**Comment by dujinyu** [comment]
Thank you very much for your reply.
I know a little about Extend LQR. elqr method needs the dynamics is known. if the dynamics is not known, how can i use elqr, when the dynamics is modeled by sampling.

**Comment by hanyas** [comment]
In the case of unknown dynamics you can use these methods either by fitting a global model and linearizing it around a given trajectory or by directly fitting time-variant linear dynamics at each time step.

Now if you don't mind I will be closing this issue, because this is not purpose of this interface
